#!/usr/bin/env bash
# generate_cask.sh - Generates Homebrew Cask files for all 130 apps
set -e

CASK_DIR="./dist/casks"
mkdir -p "$CASK_DIR"

APPS=(
    "whispertap:Global Push-to-Talk AI Dictation into any text field"
    "tokenwatch:Menu bar real-time LLM API spend & rate-limit monitor"
    "locallens-ocr:Instant screen-to-code, LaTeX, JSON, and table extractor"
    "portsentry:Menu bar active port & zombie process killer"
    "shrinkmedia:Fast batch video/audio/image compressor & GIF converter"
    "colorforge:Native eyedropper, palette builder, and contrast checker"
    "notchshelf:Smart drop-zone & staging area inside the MacBook notch"
    "audiomix:Per-app volume mixer & independent audio output routing"
    "micmute-hud:Universal hardware mic mute & camera blackout indicator"
    "promptdock:Global floating prompt HUD and snippet palette"
    "snaptile:Hyper-lightweight keyboard & edge window tiling manager"
    "purgeapp:Deep uninstaller tracking hidden caches and plists"
    "chargeguard:Battery health optimizer & custom charge threshold limiter"
    "envvault:Secure .env & API key workspace manager"
    "devtunnel-hud:Menu bar manager & traffic inspector for tunnels"
    "gitpulse:Multi-repo status bar tracker for git repositories"
    "regexforge:Native Swift live regex debugger & visual tester"
    "svgoptim:Zero-bloat SVG optimizer and SwiftUI/React component generator"
    "fontinspect:Local font viewer, glyph explorer, and variable font tester"
    "presentercam:Floating camera overlay with background blur & spotlight"
    "cleandesk-pro:1-click presentation mode and clutter cleaner"
    "screenruler:Precision on-screen pixel measurement ruler & crosshair"
    "apphop:Quick-switch popup between windows of active workspace"
    "scratchpad-hud:Always-on-top markdown floating scratchpad"
    "timebridge:Visual timezone slider and meeting overlap calculator"
    "menucleaner:Lightweight menu bar icon manager and hider"
    "metascrub:Instant EXIF, GPS location, and privacy metadata stripper"
    "bandwidthradar:Real-time per-app network download/upload monitor"
    "bluetoothautohop:Smart Bluetooth auto-disconnect and reconnect manager"
    "privatellm-bar:Ultra-lightweight menu bar local model runner"
    "petpals-desktop:Interactive desktop pet with hydration and posture nudges"
    "bonsaigrow:Virtual Zen Bonsai tree that grows with completed focus sessions"
    "deskfish-aquarium:Translucent floating desk aquarium habit tracker"
    "pomodorodragon:RPG Pomodoro egg that hatches elemental dragons"
    "codecat:Animated cat on active window edge purring on Git commits"
    "deepflow-blocker:Host and DNS-level distraction website and social app blocker"
    "zenaudio-ambience:Binaural beats, brown noise, and rain 432Hz focus generator"
    "screendimmer-focus:Spotlights active window and dims background displays"
    "breakreminder:20-20-20 eye strain rule and ergonomic stretch coach"
    "monospace-flow:Minimalist typewriter writing mode with mechanical sound cues"
    "habitgrid:GitHub-style 365-day contribution heatmaps for daily habits"
    "waterdrop-hud:Smart hydration tracker with 1-click logging and reminders"
    "postureguard:Offline Vision posture estimation to prevent slouching"
    "standup-timer:Standing desk timer with smart Bluetooth desk sync"
    "dayplanner-notch:Visual timeline of calendar events in the MacBook notch"
    "statussync:Auto-syncs Slack, Discord, and Teams status based on active app"
    "quicktweet-x:Floating HUD to draft and post to X, Bluesky, and Threads"
    "dminbox-unified:Unified menu bar badge and preview for Slack, Discord, WhatsApp"
    "streamerbanner:Animated lower-thirds and watermark for screen recordings"
    "emojiforge:Floating emoji picker with Slack/Discord custom emoji resizer"
    "pdfwhisper-ai:Instant local Q&A with PDFs via Apple Silicon embeddings"
    "gitcommit-ai:1-click conventional git commit message generator from diffs"
    "codeexplainer-hud:Highlight cryptic code or errors for plain-English explanation"
    "voicetranscribe-batch:Batch audio transcriber for podcasts and meeting files"
    "aiwallpaper-generator:Generates 4K dynamic desktop wallpapers using local CoreML"
    "jsonmaster-pro:JSON, YAML, and TOML formatter with TypeScript interface generator"
    "cronvisualizer:Visual cron expression builder and schedule debugger"
    "dockerquick-hud:Lightweight container viewer, log stream, and volume cleanup"
    "hostsmanager:1-click /etc/hosts profile switcher for dev and staging domains"
    "certsentry:SSL/TLS certificate expiration tracker for your domains"
    "keychainquick:Fast search and copy for developer SSH keys and GPG tokens"
    "curlcraft:Converts network cURL commands to Swift, Python, Node, Go code"
    "sqlitelens:Instant SQLite database file inspector and query runner"
    "npmoutdated-hud:Watches package.json across repos and alerts on vulnerabilities"
    "taillogs:Menu bar multi-file live log tailer with regex highlighting"
    "mockupsnap:1-click wraps screenshots inside 3D MacBook and iPhone frames"
    "appiconforge:Generates all iOS, macOS, watchOS, and Web icon sizes from PNG"
    "lottiepreview:Native dotLottie & JSON animation player with GIF exporter"
    "aspectratio-calc:Instant aspect ratio, DPI, and viewport sizing calculator"
    "shadowstudio:Realistic multi-layer shadow designer with SwiftUI code export"
    "duplicatefinder:Hashing-based duplicate file scanner to reclaim disk space"
    "caffeinebar:Keeps Mac awake indefinitely with custom display sleep rules"
    "hiddenfiles-toggle:1-click toggle to show/hide hidden dotfiles in Finder"
    "archiveextractor:Ultra-fast unarchiver supporting 7z, RAR, TAR, GZ, ISO"
    "clipboarddiff:Compares current clipboard with previous clipboard with diff"
    "apppermission-auditor:Inspects apps granted Camera, Mic, or Accessibility"
    "wifiradar:Displays WiFi channel congestion, RSSI, and speed in menu bar"
    "quickshare-local:P2P local network file dropper between Macs and PCs"
    "audiorecord-hud:1-click system audio + microphone recorder with MP3 export"
    "memorypurge-pro:Visual RAM pressure monitor with 1-click inactive memory purge"
    "pixelhamster-desktop:Animated pixel hamster running on a wheel in the menu bar"
    "cybergochi:Retro Tamagotchi virtual pet that eats completed to-do items"
    "deskduck:Floating rubber duck debugger that asks Socratic prompts"
    "plantnursery-hud:Virtual greenhouse where rare succulents grow with focus"
    "focussloth:Animated sloth climbing a branch in the notch during focus time"
    "zenpanda:Meditating panda companion guiding 60-second box-breathing exercises"
    "codeotter:Playful otter swimming along window edges catching fish on test passes"
    "brainwave-sync:Binaural 40Hz Gamma and Alpha wave generator for hyper-focus"
    "singletask-spotlight:Forces 1 single active window, hiding dock and menu bar"
    "antiprocrastinate-friction:10-second deliberate breathing countdown before opening sites"
    "whitenoise-mixer:Multi-track customizable soundscape mixer with rain and campfire"
    "tablimiter-pro:Restricts open tabs to max 5, auto-archiving overflowing tabs"
    "eyeblink-coach:Soft screen border halo pulse every 15s to remind users to blink"
    "focusheatmap:Live visual heatmap overlay showing app and window attention"
    "morningkickoff-hud:3-minute morning launchpad popup showing MITs and weather"
    "microjournal-bar:1-line micro-journaling in the menu bar to log quick thoughts"
    "sugar-fasting-tracker:Visual intermittent fasting timer with ketosis stage alerts"
    "sleephygiene-nudge:Automatically warms screen warmth and locks distraction apps"
    "meetingprep-countdown:Popover chime 2 minutes before calls with 1-click join link"
    "stepcounter-sync:Apple Health synced step counter progress bar in menu bar"
    "caffeinedecay-curve:Calculates active caffeine in bloodstream with cutoff warnings"
    "cliptomarkdown-thread:Converts social posts into clean Obsidian/Notion markdown"
    "podcastchapter-marker:Audio waveform scrubber to drop and export ID3 chapter markers"
    "teleprompter-hud:Translucent scrolling teleprompter for presentations and video"
    "quickpoll-creator:Generates formatted poll layouts for Twitter, LinkedIn, and Slack"
    "videothumbnail-tester:Previews thumbnails on light/dark mode social feed mocks"
    "discordrole-autoping:Quick organizer for Discord markdown, roles, and embeds"
    "watermarkmaster:Applies customizable dynamic logos and watermarks to image batches"
    "whispersubtitles-srt:Generates timestamped .srt and .vtt subtitles locally"
    "summarizeurl-ai:Offline webpage and article summarizer with 3 bullet takeaways"
    "sqlquery-ai:Translates plain English requests into optimized SQL queries"
    "localembeddings-search:Semantic vector search across local folders using CoreML"
    "diffexplainer-ai:Analyzes git diffs to generate clean release notes and changelogs"
    "readaloud-tts:Ultra-natural offline text-to-speech voice reader for articles"
    "regexgenerator-ai:Converts plain English descriptions into tested regex"
    "kubecluster-quick:Minimalist Kubernetes cluster status watcher with pod logs"
    "redislens:Menu bar Redis key-value browser, TTL inspector, and memory analyzer"
    "gitstash-manager:Visual UI for viewing, comparing, applying, and dropping stashes"
    "portforwarder-pro:SSH tunnel and local port forwarding manager with auto-reconnect"
    "apimock-server:1-click local mock HTTP server with latency simulation"
    "dotenv-diff:Compares .env.example against actual .env and flags missing keys"
    "dnslookup-hud:Instant DNS record inspector with global node propagation test"
    "httpheader-inspector:Tests HTTP response headers, CORS policies, and SSL handshakes"
    "icongrid-overlay:Pixel-perfect icon grid overlay for 512x512 and 1024x1024 icons"
    "contrastpalette-studio:Creates accessible color systems meeting WCAG AAA"
    "gradientmesh-maker:Visual multi-point gradient mesh generator with SwiftUI export"
    "diskscleaner-mini:Visualizes large downloads and node_modules for selective purge"
    "bluetoothsignal-radar:Signal strength (RSSI) monitor for AirPods and mice"
    "batterycycle-telemetry:Deep SMC battery analytics: degradation curve and cycles"
    "appquarantine-inspector:Lists quarantine attributes with 1-click gatekeeper override"
)

echo "🍺 Generating 130 Homebrew Casks..."

for item in "${APPS[@]}"; do
    name=$(echo "$item" | cut -d: -f1)
    desc=$(echo "$item" | cut -d: -f2)
    displayName=$(echo "$name" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
    
    cat <<EOF > "${CASK_DIR}/${name}.rb"
cask "${name}" do
  version "1.0.0"
  sha256 :no_check

  url "https://indiesuite.app/downloads/${name}-1.0.0.dmg"
  name "${displayName}"
  desc "${desc}"
  homepage "https://indiesuite.app/apps/${name}"

  auto_updates true
  depends_on macos: ">= :ventura"

  app "${displayName}.app"

  zap trash: [
    "~/Library/Application Support/${name}",
    "~/Library/Preferences/com.indiesuite.${name}.plist",
  ]
end
EOF
done

echo "✅ Successfully generated all 130 Homebrew Casks!"
